version: '3.8'

services:
  gunshot-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gunshot-detector
    ports:
      - "6990:6990"
    environment:
      - PYTHONUNBUFFERED=1
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SENDER_EMAIL=${SENDER_EMAIL:-sahilbhandare80@gmail.com}
      - SENDER_PASSWORD=${SENDER_PASSWORD:-hxzbgdbbfopqhrme}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-sahilbhandare79@gmail.com}
    volumes:
      - ./uploaded_audio:/app/uploaded_audio
      - ./config:/app/config
      - ./testing_chunks:/app/testing_chunks
      - ./model:/app/model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:6990/healthz"]
      interval: 30s
      timeout: 10s
      retries: 8
      start_period: 120s
